language: ruby
rvm:
  - 2.3.1
cache: bundler
branches:
  only:
  - release
before_install:
  - gem update --system
  - gem install bundler
script:
  - JEKYLL_ENV=production bundle exec jekyll build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: _site
  github-token: $GITHUB_TOKEN
  target-branch: master
  on:
    branch: release
