language: ruby
cache: bundler
branches:
  only:
  - release
before_install:
  - gem update --system
  - gem install bundler
script:
  - JEKYLL_ENV=production bundle exec jekyll build
deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: release
