#
# Jekyll configuration
#

title: Gronono
url: http://gronono.github.io
baseurl: ''

author: Arnaud Brunet
quote:
  text: La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information.
  author: Albert Einstein

social:
  github:
    title: GitHub
    icon: fab fa-github
    url: https://github.com/gronono
  stackoverflow:
    title: Stack Overflow
    icon: fab fa-stack-overflow
    url: https://stackoverflow.com/users/2909535/arnaud
  rss:
    title: RSS
    icon: fas fa-rss
    url: /feed.xml

links:
  Articles: /
  À propos: /about

disqus: gronono
comments: true

timezone: Pacific/Noumea

permalink: /:year/:month/:title

excerpt_separator: <!--more-->
plugins:
 - jekyll-paginate
 - jekyll-gist

paginate: 5
paginate_path: "page:num"

permalink: /:year/:month/:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
math_engine: mathjax

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']