apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-demo-nfs-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${gatewayIP}
    path: "/srv/nfs/demo"