name: Deploy on release
on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install nodejs
        run: sudo apt-get install nodejs
      
      - name: Check node
        run: node -v && npm -v
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/gems
          key: ${{ runner.os }}-build-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        
      - name: Build & Deploy
        uses: DavidS/jekyll-deploy@main
        with:
          target-branch: master
        env:
          JEKYLL_ENV: production
          GH_PAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}


